-- Run this once in Supabase SQL Editor to add the class chat.

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  content text not null check (char_length(trim(content)) between 1 and 500),
  created_at timestamptz not null default now()
);

alter table public.messages enable row level security;

drop policy if exists "Logged in users can read chat messages" on public.messages;
drop policy if exists "Logged in users can send chat messages" on public.messages;

create policy "Logged in users can read chat messages"
on public.messages
for select
to authenticated
using (true);

create policy "Logged in users can send chat messages"
on public.messages
for insert
to authenticated
with check (auth.uid() = user_id);

create index if not exists messages_created_at_idx
on public.messages (created_at);
